<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    NOTICE
 
    This software (or technical data) was produced for the U. S. Government 
    and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV 
    (May 2014) – Alternative IV (Dec 2007)

    (c) 2024 The MITRE Corporation. All Rights Reserved.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.mitre</groupId>
    <artifactId>buffers</artifactId>
    <version>1.0</version>

    <name>IAT Protocol Buffers</name>
    <description>Protocol Buffer definitions for the Iris Analysis Toolkit.</description>

    <properties>
        <protobuf.version>3.25.6</protobuf.version>
        <protoc.jar.maven.plugin.version>3.11.4</protoc.jar.maven.plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>${protobuf.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>${protoc.jar.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <protocArtifact>com.google.protobuf:protoc:${protobuf.version}</protocArtifact>
                            <inputDirectories>
                                <include>src/main/proto</include>
                            </inputDirectories>
                            <outputTargets>
                                <outputTarget>
                                    <type>java</type>
                                </outputTarget>
                                <outputTarget>
                                    <type>python</type>
					                <outputDirectory>${project.build.directory}/python/buffers</outputDirectory>
                                </outputTarget>
                            </outputTargets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
