<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    NOTICE
 
    This software (or technical data) was produced for the U. S. Government 
    and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV 
    (May 2014) – Alternative IV (Dec 2007)

    (c) 2024 The MITRE Corporation. All Rights Reserved.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.mitre</groupId>
    <artifactId>iris-workstation</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>buffers</module>
        <module>biqt</module>
        <module>common</module>
        <module>support</module>
        <module>web</module>
    </modules>
</project>
