#
# NOTICE
# 
# This software (or technical data) was produced for the U. S. Government
# and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV 
# (May 2014) – Alternative IV (Dec 2007)
# 
# (c) 2024 The MITRE Corporation. All Rights Reserved.
# 

broker-URI=tcp://activemq:61616
# TODO: Need to fill this out to run this locally
artemis-user=temp_value
artemis-password=temp_value
acii-request-queue=iris.acii.request
acii-response-queue=iris.acii.response
classifier-config=/etc/iwp-acii/conf.ini
allowed-img-exts=PNG,JP2,BMP,PIXMAP
acii-output-path=/tmp/
