#
# NOTICE
# 
# This software (or technical data) was produced for the U. S. Government
# and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV 
# (May 2014) – Alternative IV (Dec 2007)
# 
# (c) 2024 The MITRE Corporation. All Rights Reserved.
# 

#####################################################################
# Classifier section

RBF gamma used in training = 0.5
XML filename for upright / upside-down classifier = /usr/local/share/acii/acii-client/trainedClassifiers/SVM_UD_ALL.xml
XML filename for left / right classifier = /usr/local/share/acii/acii-client/trainedClassifiers/SVM_LR_ALL.xml
XML filename for upright / upside-down feature normalization coefficients = /usr/local/share/acii/acii-client/trainedClassifiers/FC_UD_ALL.xml
XML filename for left / right feature normalization coefficients = /usr/local/share/acii/acii-client/trainedClassifiers/FC_LR_ALL.xml

#####################################################################
# IRIS IMAGE SEGMENTATION PARAMETERS

Minimum diameter for pupil = 48
Maximum diameter for pupil = 160
Minimum diameter for iris = 180
Maximum diameter for iris = 320
