#
# NOTICE
# 
# This software (or technical data) was produced for the U. S. Government 
# and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV 
# (May 2014) – Alternative IV (Dec 2007)
# 
# (c) 2024 The MITRE Corporation. All Rights Reserved.
# 

# ActiveMQ services available
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=${ARTEMIS_USER}
spring.activemq.password=${ARTEMIS_PASSWORD}

iris.biqtService=true
iris.aciiService=true
iris.tshepiiService=true
iris.dualPDMService=true
iris.contactService=true
iris.irisAnnotationService=true
iris.pdmService=true

iris.aciiQueueRequest=iris.acii.request
iris.aciiQueueResponse=iris.acii.response
iris.biqtQueueRequest=iris.biqt.request
iris.biqtQueueResponse=iris.biqt.response
iris.tshepiiQueueRequest=iris.tshepii.request
iris.tshepiiQueueResponse=iris.tshepii.response
iris.contactQueueResponse=iris.contactdetection.response
iris.irisAnnotationQueueRequest=iris.annotation.request
iris.irisAnnotationQueueResponse=iris.annotation.response
iris.pdmQueueRequest=iris.pdm.request
iris.pdmQueueResponse=iris.pdm.response
iris.dualPDMQueueRequest=iris.dual.pdm.request
iris.dualPDMQueueResponse=iris.dual.pdm.response

iris.aciiServiceName=acii
iris.biqtServiceName=biqt
iris.tshepiiServiceName=tshepii
iris.dualPDMServiceName= dualpdm
iris.irisAnnotationServiceName=annotation
iris.pdmServiceName=pdm

# Services addresses
iris.activeMqAddress=tcp://localhost:61616
iris.iwpWebAddress=http://localhost:8080
iris.activeMqHttpAddress=http://localhost:8161/console/jolokia/read/org.apache.activemq.artemis:broker=*,component=addresses,address=*,subcomponent=queues,*/ConsumerCount,MessagesAdded,MessagesAcknowledged
iris.activeMqUserName=${ARTEMIS_USER}
iris.activeMqPassword=${ARTEMIS_PASSWORD}

#Spring Data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.datasource.url=jdbc:mysql://localhost:3306/${DATABASE_NAME}?allowPublicKeyRetrieval=TRUE&useSSL=FALSE
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.name=${DATABASE_NAME}
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Security Options
# Whether the application should respect @Secured annotations and use a login page 
iwp.security.secured=true

# The following user-password hashes are encrypted and decrypted at runtime with the configured Jasypt password.
# Use this command to decrypt a value with the standalone Jasypt tool. To encrypt a value, replace `./decrypt.sh` with `./encrypt.sh` and set `input` to the value to encrypt.
# The additional options are required because Spring Jasypt uses these defaults for decryption.
# When encrypting a hash on the command line, escape `$` characters with a `\`.
#./decrypt.sh input="STRINGTODECRYPT" password="$JASYPT_ENCRYPTOR_PASSWORD" algorithm=PBEWITHHMACSHA512ANDAES_256 verbose=true stringOutputType=base64 providerName=SunJCE saltGeneratorClassName=org.jasypt.salt.RandomSaltGenerator ivGeneratorClassName=org.jasypt.iv.RandomIvGenerator
#./encrypt.sh input="STRINGTOENCRYPT" password="$JASYPT_ENCRYPTOR_PASSWORD" algorithm=PBEWITHHMACSHA512ANDAES_256 verbose=true stringOutputType=base64 providerName=SunJCE saltGeneratorClassName=org.jasypt.salt.RandomSaltGenerator ivGeneratorClassName=org.jasypt.iv.RandomIvGenerator

# Download the tools from http://www.jasypt.org/cli.html. If the ZIP download is unavailable, see https://github.com/jasypt/jasypt/releases.

iwp.users.defaultAdminFullName=${DEFAULT_ADMIN_FULL_NAME}
iwp.users.defaultAdminTitle=${DEFAULT_ADMIN_TITLE}
iwp.users.defaultAdminEmail=${DEFAULT_ADMIN_EMAIL}
iwp.users.defaultAdminUsername=${DEFAULT_USER_USERNAME}
iwp.users.defaultAdminPassword=${DEFAULT_USER_PASSWORD}

iwp.users.defaultReviewerFullName=${DEFAULT_REVIEWER_FULL_NAME}
iwp.users.defaultReviewerTitle=${DEFAULT_REVIEWER_TITLE}
iwp.users.defaultReviewerEmail=${DEFAULT_REVIEWER_EMAIL}
iwp.users.defaultReviewerUsername=${DEFAULT_REVIEWER_USERNAME}
iwp.users.defaultReviewerPassword=${DEFAULT_REVIEWER_PASSWORD}

iwp.users.defaultSupervisorFullName=${DEFAULT_SUPERVISOR_FULL_NAME}
iwp.users.defaultSupervisorTitle=${DEFAULT_SUPERVISOR_TITLE}
iwp.users.defaultSupervisorEmail=${DEFAULT_SUPERVISOR_EMAIL}
iwp.users.defaultSupervisorUsername=${DEFAULT_SUPERVISOR_USERNAME}
iwp.users.defaultSupervisorPassword=${DEFAULT_SUPERVISOR_PASSWORD}

#file Uploads
iwp.upload.path=/tmp
iwp.image.path=/tmp

#
#   Iris Annotation Properties
#
iris.annotations.0=Unknown
iris.annotations.1=Iris
iris.annotations.2=Eyelash
iris.annotations.3=Sclera
iris.annotations.4=Pupil
iris.annotations.5=Eyebrow
iris.annotations.6=Highlight
iris.annotations.7=Border
iris.annotations.8=Crypt
iris.annotations.9=Ridge
iris.annotations.10=Contact

iris.annotationsColorHex.0=#CCCCCC
iris.annotationsColorHex.1=#0000FF
iris.annotationsColorHex.2=#FF0000
iris.annotationsColorHex.3=#FFFFFF
iris.annotationsColorHex.4=#000000
iris.annotationsColorHex.5=#00FFFF
iris.annotationsColorHex.6=#FFFF00
iris.annotationsColorHex.7=#FF00FF
iris.annotationsColorHex.8=#33FFFF
iris.annotationsColorHex.9=#FF9933
iris.annotationsColorHex.10=#00A5FF

iris.adjudicationValue.0=Match,true
iris.adjudicationValue.1=Exclude,false
iris.adjudicationValue.2=Inconclusive,true

#
#   Versioning properties
#
iris.biqtServiceVersion=1.0
iris.aciiServiceVersion=1.0
iris.tshepiiServiceVersion=1.0
iris.irisAnnotationServiceVersion=1.0
iris.pdmServiceVersion=1.0
iris.iwpBackendVersion=1.0
iris.iwpFrontendVersion=1.0


# Local Variables
iris.maxWidthImage=1000
iris.maxHeightImage=1000

server.servlet.session.tracking-modes=cookie
server.error.include-exception=true
server.error.include-stacktrace=always
spring.main.allow-circular-references = true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jms.cache.session-cache-size=5
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=50
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
log4j.logger.org.hibernate.SQL=debug
log4j.logger.org.hibernate.type.descriptor.sql=trace

# Type 1 Record defaults
iris.ver=0050
iris.tot=TOT
iris.pry=1
iris.dai=DAI
iris.ori=IWPORI0000
iris.tcn=
iris.tcr=
iris.nsr=00.00
iris.ntr=00.00
iris.dnm=NORAM
iris.dvn=EBTS 10.0
iris.apo=APO
iris.apn=APN
iris.apv=1.0

# Type 2 Record defaults
iris.atn=
iris.cix=
iris.ncr=20

# Type 17 Record defaults
iris.cga=NONE

# Profile defaults
iris.profileDai=TempDAI12
iris.profileOri=TempORI12
iris.profileAttIndicator=Attention
iris.profileSrcAgency=SRCAGENCY
iris.isProfileReportExclude=true
iris.profileDpt=DEPARTMENT
iris.profileAdd=ADDRESS
iris.profileStrokeWidth=2
iris.profileDrawColor=#127bdc
iris.profileFillColor=#333333
iris.profileNumberHistory=20

fileUploadTypesAllowed=image/jpg,image/png,image/jpeg,image/jp2,image/jp2l,image/bmp,.eft,.tiff,.sub,.ebts,.nist,.xml
maxNumUploadFiles=1000

validation.patterns.ebtsFile=^1\\.0{0,6}1:

#
#   USER NOTIFICATION PROPERTIES
#
notification.new.title=New Report
notification.new.message=A new report is available
