# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Iwp.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'Iwp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tIwp.proto\x12\x15org.mitre.iwp.buffers\"\x86\x02\n\x11ImageServiceQuery\x12\x0f\n\x07imageId\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nimageBytes\x18\x03 \x01(\x0c\x12\x45\n\timageType\x18\x04 \x01(\x0e\x32\x32.org.mitre.iwp.buffers.ImageServiceQuery.ImageType\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\"X\n\tImageType\x12\x07\n\x03PNG\x10\x00\x12\x07\n\x03JPG\x10\x01\x12\x08\n\x04JPEG\x10\x02\x12\x07\n\x03JP2\x10\x03\x12\x07\n\x03\x42MP\x10\x04\x12\x07\n\x03TIF\x10\x05\x12\x08\n\x04TIFF\x10\x06\x12\n\n\x06PIXMAP\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Iwp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGESERVICEQUERY']._serialized_start=37
  _globals['_IMAGESERVICEQUERY']._serialized_end=299
  _globals['_IMAGESERVICEQUERY_IMAGETYPE']._serialized_start=211
  _globals['_IMAGESERVICEQUERY_IMAGETYPE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
