# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Pdm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'Pdm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tPdm.proto\x12\x15org.mitre.iwp.buffers\"5\n\x11\x44ualPDMComparison\x12\r\n\x05probe\x18\x01 \x01(\x0c\x12\x11\n\tcandidate\x18\x02 \x01(\x0c\"\xe2\x01\n\x0f\x44\x65\x66ormerWrapper\x12\x0f\n\x07imageId\x18\x01 \x01(\t\x12\\\n\x13\x65yePreserveResponse\x18\x02 \x03(\x0b\x32?.org.mitre.iwp.buffers.DeformerWrapper.EyePreserveResponseEntry\x1a`\n\x18\x45yePreserveResponseEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.org.mitre.iwp.buffers.DeformedImage:\x02\x38\x01\"\xed\x01\n\rDeformedImage\x12\x11\n\timageData\x18\x01 \x01(\x0c\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x41\n\timageType\x18\x03 \x01(\x0e\x32..org.mitre.iwp.buffers.DeformedImage.ImageType\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\"X\n\tImageType\x12\x07\n\x03PNG\x10\x00\x12\x07\n\x03JPG\x10\x01\x12\x08\n\x04JPEG\x10\x02\x12\x07\n\x03JP2\x10\x03\x12\x07\n\x03\x42MP\x10\x04\x12\x07\n\x03TIF\x10\x05\x12\x08\n\x04TIFF\x10\x06\x12\n\n\x06PIXMAP\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Pdm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEFORMERWRAPPER_EYEPRESERVERESPONSEENTRY']._loaded_options = None
  _globals['_DEFORMERWRAPPER_EYEPRESERVERESPONSEENTRY']._serialized_options = b'8\001'
  _globals['_DUALPDMCOMPARISON']._serialized_start=36
  _globals['_DUALPDMCOMPARISON']._serialized_end=89
  _globals['_DEFORMERWRAPPER']._serialized_start=92
  _globals['_DEFORMERWRAPPER']._serialized_end=318
  _globals['_DEFORMERWRAPPER_EYEPRESERVERESPONSEENTRY']._serialized_start=222
  _globals['_DEFORMERWRAPPER_EYEPRESERVERESPONSEENTRY']._serialized_end=318
  _globals['_DEFORMEDIMAGE']._serialized_start=321
  _globals['_DEFORMEDIMAGE']._serialized_end=558
  _globals['_DEFORMEDIMAGE_IMAGETYPE']._serialized_start=470
  _globals['_DEFORMEDIMAGE_IMAGETYPE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
