# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IrisAnnotation.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IrisAnnotation.proto',
  package='org.mitre.iwp.buffers',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14IrisAnnotation.proto\x12\x15org.mitre.iwp.buffers\"\x8e\x02\n\x13IrisAnnotationQuery\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x04mode\x18\x02 \x01(\x0e\x32\x1f.org.mitre.iwp.buffers.ModeType\x12\x11\n\timagePath\x18\x03 \x01(\t\x12\x12\n\nimageBytes\x18\x04 \x01(\x0c\x12\x12\n\nimagesFile\x18\x05 \x01(\t\x12G\n\x13optimizationOptions\x18\x06 \x01(\x0b\x32*.org.mitre.iwp.buffers.OptimizationOptions\x12\x38\n\x0c\x63lassOptions\x18\x07 \x03(\x0b\x32\".org.mitre.iwp.buffers.ClassOption\"(\n\x13OptimizationOptions\x12\x11\n\tbatchSize\x18\x01 \x01(\x05\"8\n\x0b\x43lassOption\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\xae\x01\n\x13IrisAnnotationReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x14\n\x0cresponseCode\x18\x03 \x01(\t\x12\x17\n\x0fresponseMessage\x18\x04 \x01(\t\x12\x16\n\x0eresponseTimeMS\x18\x05 \x01(\t\x12\x32\n\x07results\x18\x06 \x03(\x0b\x32!.org.mitre.iwp.buffers.Annotation\"\\\n\nAnnotation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63olorHex\x18\x02 \x01(\t\x12\x30\n\x08polygons\x18\x03 \x03(\x0b\x32\x1e.org.mitre.iwp.buffers.Polygon\"h\n\x07Polygon\x12.\n\x07outline\x18\x01 \x01(\x0b\x32\x1d.org.mitre.iwp.buffers.Points\x12-\n\x06inline\x18\x02 \x03(\x0b\x32\x1d.org.mitre.iwp.buffers.Points\"6\n\x06Points\x12,\n\x06points\x18\x01 \x03(\x0b\x32\x1c.org.mitre.iwp.buffers.Point\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05*$\n\x08ModeType\x12\n\n\x06single\x10\x00\x12\x0c\n\x08multiple\x10\x01\x62\x06proto3'
)

_MODETYPE = _descriptor.EnumDescriptor(
  name='ModeType',
  full_name='org.mitre.iwp.buffers.ModeType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='single', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='multiple', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=884,
  serialized_end=920,
)
_sym_db.RegisterEnumDescriptor(_MODETYPE)

ModeType = enum_type_wrapper.EnumTypeWrapper(_MODETYPE)
single = 0
multiple = 1



_IRISANNOTATIONQUERY = _descriptor.Descriptor(
  name='IrisAnnotationQuery',
  full_name='org.mitre.iwp.buffers.IrisAnnotationQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imagePath', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.imagePath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageBytes', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.imageBytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imagesFile', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.imagesFile', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimizationOptions', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.optimizationOptions', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classOptions', full_name='org.mitre.iwp.buffers.IrisAnnotationQuery.classOptions', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=318,
)


_OPTIMIZATIONOPTIONS = _descriptor.Descriptor(
  name='OptimizationOptions',
  full_name='org.mitre.iwp.buffers.OptimizationOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='org.mitre.iwp.buffers.OptimizationOptions.batchSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=360,
)


_CLASSOPTION = _descriptor.Descriptor(
  name='ClassOption',
  full_name='org.mitre.iwp.buffers.ClassOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='org.mitre.iwp.buffers.ClassOption.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='org.mitre.iwp.buffers.ClassOption.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.mitre.iwp.buffers.ClassOption.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=418,
)


_IRISANNOTATIONREPLY = _descriptor.Descriptor(
  name='IrisAnnotationReply',
  full_name='org.mitre.iwp.buffers.IrisAnnotationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.responseCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.responseMessage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseTimeMS', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.responseTimeMS', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='results', full_name='org.mitre.iwp.buffers.IrisAnnotationReply.results', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=595,
)


_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='org.mitre.iwp.buffers.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.mitre.iwp.buffers.Annotation.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colorHex', full_name='org.mitre.iwp.buffers.Annotation.colorHex', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='polygons', full_name='org.mitre.iwp.buffers.Annotation.polygons', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=689,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='org.mitre.iwp.buffers.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='outline', full_name='org.mitre.iwp.buffers.Polygon.outline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inline', full_name='org.mitre.iwp.buffers.Polygon.inline', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=795,
)


_POINTS = _descriptor.Descriptor(
  name='Points',
  full_name='org.mitre.iwp.buffers.Points',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='org.mitre.iwp.buffers.Points.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=797,
  serialized_end=851,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='org.mitre.iwp.buffers.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='org.mitre.iwp.buffers.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='org.mitre.iwp.buffers.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=853,
  serialized_end=882,
)

_IRISANNOTATIONQUERY.fields_by_name['mode'].enum_type = _MODETYPE
_IRISANNOTATIONQUERY.fields_by_name['optimizationOptions'].message_type = _OPTIMIZATIONOPTIONS
_IRISANNOTATIONQUERY.fields_by_name['classOptions'].message_type = _CLASSOPTION
_IRISANNOTATIONREPLY.fields_by_name['results'].message_type = _ANNOTATION
_ANNOTATION.fields_by_name['polygons'].message_type = _POLYGON
_POLYGON.fields_by_name['outline'].message_type = _POINTS
_POLYGON.fields_by_name['inline'].message_type = _POINTS
_POINTS.fields_by_name['points'].message_type = _POINT
DESCRIPTOR.message_types_by_name['IrisAnnotationQuery'] = _IRISANNOTATIONQUERY
DESCRIPTOR.message_types_by_name['OptimizationOptions'] = _OPTIMIZATIONOPTIONS
DESCRIPTOR.message_types_by_name['ClassOption'] = _CLASSOPTION
DESCRIPTOR.message_types_by_name['IrisAnnotationReply'] = _IRISANNOTATIONREPLY
DESCRIPTOR.message_types_by_name['Annotation'] = _ANNOTATION
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Points'] = _POINTS
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.enum_types_by_name['ModeType'] = _MODETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IrisAnnotationQuery = _reflection.GeneratedProtocolMessageType('IrisAnnotationQuery', (_message.Message,), {
  'DESCRIPTOR' : _IRISANNOTATIONQUERY,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.IrisAnnotationQuery)
  })
_sym_db.RegisterMessage(IrisAnnotationQuery)

OptimizationOptions = _reflection.GeneratedProtocolMessageType('OptimizationOptions', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZATIONOPTIONS,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.OptimizationOptions)
  })
_sym_db.RegisterMessage(OptimizationOptions)

ClassOption = _reflection.GeneratedProtocolMessageType('ClassOption', (_message.Message,), {
  'DESCRIPTOR' : _CLASSOPTION,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.ClassOption)
  })
_sym_db.RegisterMessage(ClassOption)

IrisAnnotationReply = _reflection.GeneratedProtocolMessageType('IrisAnnotationReply', (_message.Message,), {
  'DESCRIPTOR' : _IRISANNOTATIONREPLY,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.IrisAnnotationReply)
  })
_sym_db.RegisterMessage(IrisAnnotationReply)

Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATION,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.Annotation)
  })
_sym_db.RegisterMessage(Annotation)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

Points = _reflection.GeneratedProtocolMessageType('Points', (_message.Message,), {
  'DESCRIPTOR' : _POINTS,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.Points)
  })
_sym_db.RegisterMessage(Points)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'IrisAnnotation_pb2'
  # @@protoc_insertion_point(class_scope:org.mitre.iwp.buffers.Point)
  })
_sym_db.RegisterMessage(Point)


# @@protoc_insertion_point(module_scope)
